/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-10-19 08:31:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.1.6.RELEASE.jar", Long.valueOf(1467197210000L));
    _jspx_dependants.put("/WEB-INF/tags/template/js.tag", Long.valueOf(1476865323000L));
    _jspx_dependants.put("jar:file:/Users/i076218/Documents/02IDE/workspaces/pp/third/thrid-web/target/thrid-web/WEB-INF/lib/spring-webmvc-4.1.6.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1427245024000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1431168206000L));
    _jspx_dependants.put("/WEB-INF/tags/template/css.tag", Long.valueOf(1476865904000L));
    _jspx_dependants.put("jar:file:/Users/i076218/Documents/02IDE/workspaces/pp/third/thrid-web/target/thrid-web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    ");
      if (_jspx_meth_template_005fcss_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"easyui-layout\" style=\"width:300px; height:300px;\">\n");
      out.write("    <div region=\"north\">顶部</div>\n");
      out.write("    <div region=\"west\" style=\"width:100px\">左侧</div>\n");
      out.write("    <div region=\"center\">主工作区</div>\n");
      out.write("    <div region=\"east\" style=\"width:100px\">右侧</div>\n");
      out.write("    <div region=\"south\">底部</div>\n");
      out.write("</div>\n");
      out.write("<!-- \t<div> -->\n");
      out.write("<!-- \t\t<h1>spring login deploy test</h1> -->\n");
      out.write("\n");
      out.write("<!-- \t\t\tmethod=\"post\" class=\"form-signin\"> -->\n");
      out.write("<!-- \t\t\t<input type=\"text\" name=\"username\"></input> <input type=\"password\" -->\n");
      out.write("<!-- \t\t\t\tname=\"password\"></input> <input type=\"submit\" value=\"login\" /> -->\n");
      out.write("<!-- \t\t</form> -->\n");
      out.write("<!-- \t</div> -->\n");
      out.write("\t");
      if (_jspx_meth_template_005fjs_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_template_005fcss_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  template:css
    org.apache.jsp.tag.web.template.css_tag _jspx_th_template_005fcss_005f0 = (new org.apache.jsp.tag.web.template.css_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_template_005fcss_005f0);
    _jspx_th_template_005fcss_005f0.setJspContext(_jspx_page_context);
    _jspx_th_template_005fcss_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_template_005fcss_005f0);
    return false;
  }

  private boolean _jspx_meth_template_005fjs_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  template:js
    org.apache.jsp.tag.web.template.js_tag _jspx_th_template_005fjs_005f0 = (new org.apache.jsp.tag.web.template.js_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_template_005fjs_005f0);
    _jspx_th_template_005fjs_005f0.setJspContext(_jspx_page_context);
    _jspx_th_template_005fjs_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_template_005fjs_005f0);
    return false;
  }
}
