package com.third.dao.impl;

import com.third.model.UserGroup;
import com.third.model.UserGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGroupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	int countByExample(UserGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	int deleteByExample(UserGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	int deleteByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	int insert(UserGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	int insertSelective(UserGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	List<UserGroup> selectByExample(UserGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	UserGroup selectByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	int updateByExampleSelective(@Param("record") UserGroup record,
			@Param("example") UserGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	int updateByExample(@Param("record") UserGroup record,
			@Param("example") UserGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	int updateByPrimaryKeySelective(UserGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_group
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	int updateByPrimaryKey(UserGroup record);
}