package com.third.model;
// Generated Nov 21, 2018 10:12:13 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CategoryModel generated by hbm2java
 */
public class CategoryModel  implements java.io.Serializable {


     private String pk;
     private String code;
     private String name;
     private Date modificationTime;
     private Date createTime;

    public CategoryModel() {
    }

    public CategoryModel(String code, String name, Date modificationTime, Date createTime) {
       this.code = code;
       this.name = name;
       this.modificationTime = modificationTime;
       this.createTime = createTime;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


