package com.third.model;
// Generated Nov 21, 2018 10:12:13 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Collection;

/**
 * CityModel generated by hbm2java
 */
public class CityModel  implements java.io.Serializable {


     private String isoCode;
     private String name;
     private RegionModel region;
     private Collection districts = new ArrayList(0);

    public CityModel() {
    }

	
    public CityModel(String isoCode) {
        this.isoCode = isoCode;
    }
    public CityModel(String isoCode, String name, RegionModel region, Collection districts) {
       this.isoCode = isoCode;
       this.name = name;
       this.region = region;
       this.districts = districts;
    }
   
    public String getIsoCode() {
        return this.isoCode;
    }
    
    public void setIsoCode(String isoCode) {
        this.isoCode = isoCode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public RegionModel getRegion() {
        return this.region;
    }
    
    public void setRegion(RegionModel region) {
        this.region = region;
    }
    public Collection getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Collection districts) {
        this.districts = districts;
    }




}


