package com.third.model;
// Generated Nov 9, 2016 10:56:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MaterialModel generated by hbm2java
 */
public class MaterialModel  implements java.io.Serializable {


     private String pk;
     private String materialno;
     private String materialtext;
     private String materialtype;
     private Date createTime;
     private Date modificationTime;
     private UserModel createdBy;

    public MaterialModel() {
    }

    public MaterialModel(String materialno, String materialtext, String materialtype, Date createTime, Date modificationTime, UserModel createdBy) {
       this.materialno = materialno;
       this.materialtext = materialtext;
       this.materialtype = materialtype;
       this.createTime = createTime;
       this.modificationTime = modificationTime;
       this.createdBy = createdBy;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getMaterialno() {
        return this.materialno;
    }
    
    public void setMaterialno(String materialno) {
        this.materialno = materialno;
    }
    public String getMaterialtext() {
        return this.materialtext;
    }
    
    public void setMaterialtext(String materialtext) {
        this.materialtext = materialtext;
    }
    public String getMaterialtype() {
        return this.materialtype;
    }
    
    public void setMaterialtype(String materialtype) {
        this.materialtype = materialtype;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
    public UserModel getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(UserModel createdBy) {
        this.createdBy = createdBy;
    }




}


