package com.third.model;
// Generated Dec 14, 2016 10:14:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderEntryModel generated by hbm2java
 */
public class OrderEntryModel  implements java.io.Serializable {


     private String pk;
     private Integer entryNo;
     private String style;
     private String itemCategory;
     private ProductModel product;
     private String productTitle;
     private Integer quantity;
     private String designer;
     private String customerName;
     private Date deliveryDate;
     private Date sizeDate;
     private Date tryDate;
     private String comment;
     private String sizeDetails;
     private String sizeImage;
     private OrderModel order;
     private Date modificationTime;
     private Date createTime;
     private UserModel createdBy;

    public OrderEntryModel() {
    }

    public OrderEntryModel(Integer entryNo, String style, String itemCategory, ProductModel product, String productTitle, Integer quantity, String designer, String customerName, Date deliveryDate, Date sizeDate, Date tryDate, String comment, String sizeDetails, String sizeImage, OrderModel order, Date modificationTime, Date createTime, UserModel createdBy) {
       this.entryNo = entryNo;
       this.style = style;
       this.itemCategory = itemCategory;
       this.product = product;
       this.productTitle = productTitle;
       this.quantity = quantity;
       this.designer = designer;
       this.customerName = customerName;
       this.deliveryDate = deliveryDate;
       this.sizeDate = sizeDate;
       this.tryDate = tryDate;
       this.comment = comment;
       this.sizeDetails = sizeDetails;
       this.sizeImage = sizeImage;
       this.order = order;
       this.modificationTime = modificationTime;
       this.createTime = createTime;
       this.createdBy = createdBy;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public Integer getEntryNo() {
        return this.entryNo;
    }
    
    public void setEntryNo(Integer entryNo) {
        this.entryNo = entryNo;
    }
    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }
    public String getItemCategory() {
        return this.itemCategory;
    }
    
    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }
    public ProductModel getProduct() {
        return this.product;
    }
    
    public void setProduct(ProductModel product) {
        this.product = product;
    }
    public String getProductTitle() {
        return this.productTitle;
    }
    
    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public String getDesigner() {
        return this.designer;
    }
    
    public void setDesigner(String designer) {
        this.designer = designer;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public Date getSizeDate() {
        return this.sizeDate;
    }
    
    public void setSizeDate(Date sizeDate) {
        this.sizeDate = sizeDate;
    }
    public Date getTryDate() {
        return this.tryDate;
    }
    
    public void setTryDate(Date tryDate) {
        this.tryDate = tryDate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getSizeDetails() {
        return this.sizeDetails;
    }
    
    public void setSizeDetails(String sizeDetails) {
        this.sizeDetails = sizeDetails;
    }
    public String getSizeImage() {
        return this.sizeImage;
    }
    
    public void setSizeImage(String sizeImage) {
        this.sizeImage = sizeImage;
    }
    public OrderModel getOrder() {
        return this.order;
    }
    
    public void setOrder(OrderModel order) {
        this.order = order;
    }
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public UserModel getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(UserModel createdBy) {
        this.createdBy = createdBy;
    }




}


