package com.third.model;
// Generated Nov 10, 2016 4:52:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * OrderModel generated by hbm2java
 */
public class OrderModel  implements java.io.Serializable {


     private String pk;
     private String code;
     private String coSalesperson;
     private String customerName;
     private String cellphone;
     private String qq;
     private Date weddingDay;
     private Date orderDate;
     private Date tryDate;
     private Date photoDate;
     private Date deliveryDate;
     private Integer approval;
     private String comment;
     private BigDecimal receiveable;
     private BigDecimal openamount;
     private Integer status;
     private String paymentMethod;
     private CustomerModel customer;
     private UserModel salesperson;
     private SourceModel source;
     private StoreModel store;
     private List payments = new ArrayList(0);
     private List orderEntries = new ArrayList(0);

    public OrderModel() {
    }

    public OrderModel(String code, String coSalesperson, String customerName, String cellphone, String qq, Date weddingDay, Date orderDate, Date tryDate, Date photoDate, Date deliveryDate, Integer approval, String comment, BigDecimal receiveable, BigDecimal openamount, Integer status, String paymentMethod, CustomerModel customer, UserModel salesperson, SourceModel source, StoreModel store, List payments, List orderEntries) {
       this.code = code;
       this.coSalesperson = coSalesperson;
       this.customerName = customerName;
       this.cellphone = cellphone;
       this.qq = qq;
       this.weddingDay = weddingDay;
       this.orderDate = orderDate;
       this.tryDate = tryDate;
       this.photoDate = photoDate;
       this.deliveryDate = deliveryDate;
       this.approval = approval;
       this.comment = comment;
       this.receiveable = receiveable;
       this.openamount = openamount;
       this.status = status;
       this.paymentMethod = paymentMethod;
       this.customer = customer;
       this.salesperson = salesperson;
       this.source = source;
       this.store = store;
       this.payments = payments;
       this.orderEntries = orderEntries;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getCoSalesperson() {
        return this.coSalesperson;
    }
    
    public void setCoSalesperson(String coSalesperson) {
        this.coSalesperson = coSalesperson;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }
    public String getQq() {
        return this.qq;
    }
    
    public void setQq(String qq) {
        this.qq = qq;
    }
    public Date getWeddingDay() {
        return this.weddingDay;
    }
    
    public void setWeddingDay(Date weddingDay) {
        this.weddingDay = weddingDay;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Date getTryDate() {
        return this.tryDate;
    }
    
    public void setTryDate(Date tryDate) {
        this.tryDate = tryDate;
    }
    public Date getPhotoDate() {
        return this.photoDate;
    }
    
    public void setPhotoDate(Date photoDate) {
        this.photoDate = photoDate;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public Integer getApproval() {
        return this.approval;
    }
    
    public void setApproval(Integer approval) {
        this.approval = approval;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public BigDecimal getReceiveable() {
        return this.receiveable;
    }
    
    public void setReceiveable(BigDecimal receiveable) {
        this.receiveable = receiveable;
    }
    public BigDecimal getOpenamount() {
        return this.openamount;
    }
    
    public void setOpenamount(BigDecimal openamount) {
        this.openamount = openamount;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public CustomerModel getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(CustomerModel customer) {
        this.customer = customer;
    }
    public UserModel getSalesperson() {
        return this.salesperson;
    }
    
    public void setSalesperson(UserModel salesperson) {
        this.salesperson = salesperson;
    }
    public SourceModel getSource() {
        return this.source;
    }
    
    public void setSource(SourceModel source) {
        this.source = source;
    }
    public StoreModel getStore() {
        return this.store;
    }
    
    public void setStore(StoreModel store) {
        this.store = store;
    }
    public List getPayments() {
        return this.payments;
    }
    
    public void setPayments(List payments) {
        this.payments = payments;
    }
    public List getOrderEntries() {
        return this.orderEntries;
    }
    
    public void setOrderEntries(List orderEntries) {
        this.orderEntries = orderEntries;
    }




}


