package com.third.model;
// Generated Nov 21, 2018 10:12:13 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OrderEntryModel generated by hbm2java
 */
public class OrderEntryModel  implements java.io.Serializable {


     private String pk;
     private String code;
     private Integer entryNo;
     private String externalId;
     private String style;
     private String itemCategory;
     private Boolean isSizeItem;
     private ProductModel product;
     private String productTitle;
     private Integer quantity;
     private UserModel designer;
     private String customerName;
     private Integer status;
     private StoreModel store;
     private Date deliveryDate;
     private Date sizeDate;
     private Date tryDate;
     private Date scheduleDate;
     private Date actualTryDate;
     private Boolean needTry;
     private Boolean exported;
     private String comment;
     private String sizeDetails;
     private String sizeImage;
     private OrderModel order;
     private Date modificationTime;
     private Date createTime;
     private UserModel createdBy;

    public OrderEntryModel() {
    }

	
    public OrderEntryModel(String pk) {
        this.pk = pk;
    }
    public OrderEntryModel(String pk, String code, Integer entryNo, String externalId, String style, String itemCategory, Boolean isSizeItem, ProductModel product, String productTitle, Integer quantity, UserModel designer, String customerName, Integer status, StoreModel store, Date deliveryDate, Date sizeDate, Date tryDate, Date scheduleDate, Date actualTryDate, Boolean needTry, Boolean exported, String comment, String sizeDetails, String sizeImage, OrderModel order, Date modificationTime, Date createTime, UserModel createdBy) {
       this.pk = pk;
       this.code = code;
       this.entryNo = entryNo;
       this.externalId = externalId;
       this.style = style;
       this.itemCategory = itemCategory;
       this.isSizeItem = isSizeItem;
       this.product = product;
       this.productTitle = productTitle;
       this.quantity = quantity;
       this.designer = designer;
       this.customerName = customerName;
       this.status = status;
       this.store = store;
       this.deliveryDate = deliveryDate;
       this.sizeDate = sizeDate;
       this.tryDate = tryDate;
       this.scheduleDate = scheduleDate;
       this.actualTryDate = actualTryDate;
       this.needTry = needTry;
       this.exported = exported;
       this.comment = comment;
       this.sizeDetails = sizeDetails;
       this.sizeImage = sizeImage;
       this.order = order;
       this.modificationTime = modificationTime;
       this.createTime = createTime;
       this.createdBy = createdBy;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public Integer getEntryNo() {
        return this.entryNo;
    }
    
    public void setEntryNo(Integer entryNo) {
        this.entryNo = entryNo;
    }
    public String getExternalId() {
        return this.externalId;
    }
    
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }
    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }
    public String getItemCategory() {
        return this.itemCategory;
    }
    
    public void setItemCategory(String itemCategory) {
        this.itemCategory = itemCategory;
    }
    public Boolean getIsSizeItem() {
        return this.isSizeItem;
    }
    
    public void setIsSizeItem(Boolean isSizeItem) {
        this.isSizeItem = isSizeItem;
    }
    public ProductModel getProduct() {
        return this.product;
    }
    
    public void setProduct(ProductModel product) {
        this.product = product;
    }
    public String getProductTitle() {
        return this.productTitle;
    }
    
    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public UserModel getDesigner() {
        return this.designer;
    }
    
    public void setDesigner(UserModel designer) {
        this.designer = designer;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public StoreModel getStore() {
        return this.store;
    }
    
    public void setStore(StoreModel store) {
        this.store = store;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public Date getSizeDate() {
        return this.sizeDate;
    }
    
    public void setSizeDate(Date sizeDate) {
        this.sizeDate = sizeDate;
    }
    public Date getTryDate() {
        return this.tryDate;
    }
    
    public void setTryDate(Date tryDate) {
        this.tryDate = tryDate;
    }
    public Date getScheduleDate() {
        return this.scheduleDate;
    }
    
    public void setScheduleDate(Date scheduleDate) {
        this.scheduleDate = scheduleDate;
    }
    public Date getActualTryDate() {
        return this.actualTryDate;
    }
    
    public void setActualTryDate(Date actualTryDate) {
        this.actualTryDate = actualTryDate;
    }
    public Boolean getNeedTry() {
        return this.needTry;
    }
    
    public void setNeedTry(Boolean needTry) {
        this.needTry = needTry;
    }
    public Boolean getExported() {
        return this.exported;
    }
    
    public void setExported(Boolean exported) {
        this.exported = exported;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getSizeDetails() {
        return this.sizeDetails;
    }
    
    public void setSizeDetails(String sizeDetails) {
        this.sizeDetails = sizeDetails;
    }
    public String getSizeImage() {
        return this.sizeImage;
    }
    
    public void setSizeImage(String sizeImage) {
        this.sizeImage = sizeImage;
    }
    public OrderModel getOrder() {
        return this.order;
    }
    
    public void setOrder(OrderModel order) {
        this.order = order;
    }
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public UserModel getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(UserModel createdBy) {
        this.createdBy = createdBy;
    }




}


