package com.third.model;
// Generated Nov 21, 2018 10:12:13 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductModel generated by hbm2java
 */
public class ProductModel  implements java.io.Serializable {


     private String pk;
     private String code;
     private String producttitle;
     private String producttype;
     private ProductGroupModel productGroup;
     private CategoryModel category;
     private Date modificationTime;
     private Date createTime;
     private UserModel createdBy;

    public ProductModel() {
    }

    public ProductModel(String code, String producttitle, String producttype, ProductGroupModel productGroup, CategoryModel category, Date modificationTime, Date createTime, UserModel createdBy) {
       this.code = code;
       this.producttitle = producttitle;
       this.producttype = producttype;
       this.productGroup = productGroup;
       this.category = category;
       this.modificationTime = modificationTime;
       this.createTime = createTime;
       this.createdBy = createdBy;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getProducttitle() {
        return this.producttitle;
    }
    
    public void setProducttitle(String producttitle) {
        this.producttitle = producttitle;
    }
    public String getProducttype() {
        return this.producttype;
    }
    
    public void setProducttype(String producttype) {
        this.producttype = producttype;
    }
    public ProductGroupModel getProductGroup() {
        return this.productGroup;
    }
    
    public void setProductGroup(ProductGroupModel productGroup) {
        this.productGroup = productGroup;
    }
    public CategoryModel getCategory() {
        return this.category;
    }
    
    public void setCategory(CategoryModel category) {
        this.category = category;
    }
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public UserModel getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(UserModel createdBy) {
        this.createdBy = createdBy;
    }




}


