package com.third.model;
// Generated Nov 28, 2016 4:34:25 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Collection;

/**
 * RoleModel generated by hbm2java
 */
public class RoleModel  implements java.io.Serializable {


     private String pk;
     private String roleId;
     private String roleName;
     private String description;
     private Collection menus = new ArrayList(0);

    public RoleModel() {
    }

    public RoleModel(String roleId, String roleName, String description, Collection menus) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.description = description;
       this.menus = menus;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Collection getMenus() {
        return this.menus;
    }
    
    public void setMenus(Collection menus) {
        this.menus = menus;
    }




}


