package com.third.model;
// Generated Nov 21, 2018 10:12:13 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * SalesQuotationModel generated by hbm2java
 */
public class SalesQuotationModel  implements java.io.Serializable {


     private String pk;
     private String customerName;
     private String cellphone;
     private String contactinfo;
     private Date weddingDate;
     private Date tryDate;
     private Date photoDate;
     private Date deliveryDate;
     private String coSalesperson;
     private String comment;
     private BigDecimal totalamount;
     private BigDecimal paidamount;
     private String paymentMethod;
     private Date createDate;
     private String orderCode;
     private SourceModel source;
     private Date modificationTime;
     private Date createTime;
     private UserModel createdBy;

    public SalesQuotationModel() {
    }

    public SalesQuotationModel(String customerName, String cellphone, String contactinfo, Date weddingDate, Date tryDate, Date photoDate, Date deliveryDate, String coSalesperson, String comment, BigDecimal totalamount, BigDecimal paidamount, String paymentMethod, Date createDate, String orderCode, SourceModel source, Date modificationTime, Date createTime, UserModel createdBy) {
       this.customerName = customerName;
       this.cellphone = cellphone;
       this.contactinfo = contactinfo;
       this.weddingDate = weddingDate;
       this.tryDate = tryDate;
       this.photoDate = photoDate;
       this.deliveryDate = deliveryDate;
       this.coSalesperson = coSalesperson;
       this.comment = comment;
       this.totalamount = totalamount;
       this.paidamount = paidamount;
       this.paymentMethod = paymentMethod;
       this.createDate = createDate;
       this.orderCode = orderCode;
       this.source = source;
       this.modificationTime = modificationTime;
       this.createTime = createTime;
       this.createdBy = createdBy;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCellphone() {
        return this.cellphone;
    }
    
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }
    public String getContactinfo() {
        return this.contactinfo;
    }
    
    public void setContactinfo(String contactinfo) {
        this.contactinfo = contactinfo;
    }
    public Date getWeddingDate() {
        return this.weddingDate;
    }
    
    public void setWeddingDate(Date weddingDate) {
        this.weddingDate = weddingDate;
    }
    public Date getTryDate() {
        return this.tryDate;
    }
    
    public void setTryDate(Date tryDate) {
        this.tryDate = tryDate;
    }
    public Date getPhotoDate() {
        return this.photoDate;
    }
    
    public void setPhotoDate(Date photoDate) {
        this.photoDate = photoDate;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public String getCoSalesperson() {
        return this.coSalesperson;
    }
    
    public void setCoSalesperson(String coSalesperson) {
        this.coSalesperson = coSalesperson;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public BigDecimal getTotalamount() {
        return this.totalamount;
    }
    
    public void setTotalamount(BigDecimal totalamount) {
        this.totalamount = totalamount;
    }
    public BigDecimal getPaidamount() {
        return this.paidamount;
    }
    
    public void setPaidamount(BigDecimal paidamount) {
        this.paidamount = paidamount;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getOrderCode() {
        return this.orderCode;
    }
    
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }
    public SourceModel getSource() {
        return this.source;
    }
    
    public void setSource(SourceModel source) {
        this.source = source;
    }
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public UserModel getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(UserModel createdBy) {
        this.createdBy = createdBy;
    }




}


