package com.third.model;
// Generated Dec 9, 2016 11:47:25 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SourceModel generated by hbm2java
 */
public class SourceModel  implements java.io.Serializable {


     private String pk;
     private String name;
     private String type;
     private Date modificationTime;
     private Date createTime;

    public SourceModel() {
    }

    public SourceModel(String name, String type, Date modificationTime, Date createTime) {
       this.name = name;
       this.type = type;
       this.modificationTime = modificationTime;
       this.createTime = createTime;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }




}


