package com.third.model;
// Generated Nov 21, 2018 10:12:13 AM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;

/**
 * StoreModel generated by hbm2java
 */
public class StoreModel  implements java.io.Serializable {


     private String pk;
     private String id;
     private String name;
     private String phone;
     private Date modificationTime;
     private Date createTime;
     private AddressModel address;
     private Collection sources = new ArrayList(0);

    public StoreModel() {
    }

    public StoreModel(String id, String name, String phone, Date modificationTime, Date createTime, AddressModel address, Collection sources) {
       this.id = id;
       this.name = name;
       this.phone = phone;
       this.modificationTime = modificationTime;
       this.createTime = createTime;
       this.address = address;
       this.sources = sources;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getModificationTime() {
        return this.modificationTime;
    }
    
    public void setModificationTime(Date modificationTime) {
        this.modificationTime = modificationTime;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public AddressModel getAddress() {
        return this.address;
    }
    
    public void setAddress(AddressModel address) {
        this.address = address;
    }
    public Collection getSources() {
        return this.sources;
    }
    
    public void setSources(Collection sources) {
        this.sources = sources;
    }




}


