package com.third.model;
// Generated Nov 10, 2016 4:52:00 PM by Hibernate Tools 4.3.1



/**
 * StoreModel generated by hbm2java
 */
public class StoreModel  implements java.io.Serializable {


     private String pk;
     private String id;
     private String name;
     private String phone;
     private AddressModel address;

    public StoreModel() {
    }

    public StoreModel(String id, String name, String phone, AddressModel address) {
       this.id = id;
       this.name = name;
       this.phone = phone;
       this.address = address;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public AddressModel getAddress() {
        return this.address;
    }
    
    public void setAddress(AddressModel address) {
        this.address = address;
    }




}


