package com.third.model;
// Generated Aug 23, 2017 5:05:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SubscribeModel generated by hbm2java
 */
public class SubscribeModel  implements java.io.Serializable {


     private String openId;
     private String nickName;
     private Integer sex;
     private String city;
     private String country;
     private String province;
     private String headimgurl;
     private Date time;
     private String unionId;

    public SubscribeModel() {
    }

	
    public SubscribeModel(String openId) {
        this.openId = openId;
    }
    public SubscribeModel(String openId, String nickName, Integer sex, String city, String country, String province, String headimgurl, Date time, String unionId) {
       this.openId = openId;
       this.nickName = nickName;
       this.sex = sex;
       this.city = city;
       this.country = country;
       this.province = province;
       this.headimgurl = headimgurl;
       this.time = time;
       this.unionId = unionId;
    }
   
    public String getOpenId() {
        return this.openId;
    }
    
    public void setOpenId(String openId) {
        this.openId = openId;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getHeadimgurl() {
        return this.headimgurl;
    }
    
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getUnionId() {
        return this.unionId;
    }
    
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }




}


