package com.third.model;

// Generated Oct 23, 2016 12:43:16 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer pk;
	private String id;
	private String password;
	private String name;
	private Set userGroups = new HashSet(0);

	public User() {
	}

	public User(String id, String password, String name, Set userGroups) {
		this.id = id;
		this.password = password;
		this.name = name;
		this.userGroups = userGroups;
	}

	public Integer getPk() {
		return this.pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set userGroups) {
		this.userGroups = userGroups;
	}

}
