package com.third.model;
// Generated Oct 31, 2016 10:31:11 PM by Hibernate Tools 4.3.1



/**
 * UserModel generated by hbm2java
 */
public class UserModel  implements java.io.Serializable {


     private String pk;
     private String userId;
     private String password;
     private String name;
     private UserGroupModel userGroup;

    public UserModel() {
    }

    public UserModel(String userId, String password, String name, UserGroupModel userGroup) {
       this.userId = userId;
       this.password = password;
       this.name = name;
       this.userGroup = userGroup;
    }
   
    public String getPk() {
        return this.pk;
    }
    
    public void setPk(String pk) {
        this.pk = pk;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public UserGroupModel getUserGroup() {
        return this.userGroup;
    }
    
    public void setUserGroup(UserGroupModel userGroup) {
        this.userGroup = userGroup;
    }




}


