package com.third.model;

// Generated Oct 23, 2016 12:43:16 AM by Hibernate Tools 4.3.1

/**
 * UserGroup generated by hbm2java
 */
public class UserGroup implements java.io.Serializable {

	private Integer pk;
	private String id;
	private String name;

	public UserGroup() {
	}

	public UserGroup(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Integer getPk() {
		return this.pk;
	}

	public void setPk(Integer pk) {
		this.pk = pk;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
