package com.third.model;

public class UserGroup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_group.pk
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	private Integer pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_group.id
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_group.name
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_group.pk
	 * @return  the value of user_group.pk
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_group.pk
	 * @param pk  the value for user_group.pk
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public void setPk(Integer pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_group.id
	 * @return  the value of user_group.id
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_group.id
	 * @param id  the value for user_group.id
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_group.name
	 * @return  the value of user_group.name
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_group.name
	 * @param name  the value for user_group.name
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}
}