package com.third.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.pk
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	private Integer pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userid
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.pk
	 * @return  the value of user.pk
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.pk
	 * @param pk  the value for user.pk
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	public void setPk(Integer pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userid
	 * @return  the value of user.userid
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userid
	 * @param userid  the value for user.userid
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Mon Oct 17 15:27:39 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}