package com.third.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.pk
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	private Integer pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.usergroup
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	private UserGroup usergroup;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.pk
	 * @return  the value of user.pk
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.pk
	 * @param pk  the value for user.pk
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public void setPk(Integer pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.usergroup
	 * @return  the value of user.usergroup
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public UserGroup getUsergroup() {
		return usergroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.usergroup
	 * @param usergroup  the value for user.usergroup
	 * @mbggenerated  Fri Oct 21 23:34:23 CST 2016
	 */
	public void setUsergroup(UserGroup usergroup) {
		this.usergroup = usergroup;
	}
}